experiment/urls.py
from django.conf.urls import patterns, include, url
import views
import views_s3

urlpatterns = patterns("",
    url(r"^$", views.ExperimentHome.as_view(), name="home"),
    url(r"^create/$", views.ExperimentCreate.as_view(), name="create"),
    url(r"^(?P<experiment_id>\d+)/$", views.ExperimentDetail.as_view(), name="detail"),
    url(r"^(?P<experiment_id>\d+)/update/$", views.ExperimentUpdate.as_view(), name="update"),

    url(r"^(?P<experiment_id>\d+)/image/$", views.ExperimentDetail.as_view(), name="image-home"),
    url(r"^(?P<experiment_id>\d+)/image/upload/$", views_s3.index, name="image-upload"),
    url(r"^(?P<experiment_id>\d+)/image/upload/init_multipart/$", views_s3.init_multipart, name="image-upload-init"),
    url(r"^(?P<experiment_id>\d+)/image/upload/send_chunk/$", views_s3.send_chunk, name="image-upload-send"),
    url(r"^(?P<experiment_id>\d+)/image/upload/complete_file/$", views_s3.complete_file, name="image-upload-complete"),
    url(r"^(?P<experiment_id>\d+)/image/upload/report/$", views_s3.report, name="image-upload-report")
)

experiment_repo/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url = reverse_lazy("experiment:home")), name = "repo-home"),
    url(r"^experiment/", include("experiment.urls", namespace = "experiment")),
    url(r"^users/", include("experiment_user.urls", namespace = "experiment_user")),
    url(r"^accounts/", include("allauth.urls")),

    # For admin
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

experiment_repo/templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% block title_text %} {% endblock %} - Experiment Repository {% endblock %} </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="../../assets/js/html5shiv.js"></script>
        <script src="../../assets/js/respond.min.js"></script>
        <![endif]-->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        
        <style type="text/css">
            .footer {
                color: #555555;
                text-align: center;
            }
            .footer p {
                font-size: 12px;
            }
        </style>
        
        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            {% block header %}
            <nav class="navbar navbar-default" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'repo-home' %}">Experiment Repository</a>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li {% block navbar-home-attr %} {% endblock %}><a href="{% url 'repo-home' %}">Home</a></li>
                        <li {% block navbar-user-attr %} {% endblock %}><a href="{% url 'experiment_user:home' %}">Users</a></li>
                        <li {% block navbar-create-attr %} {% endblock %}><a href="{% url 'experiment:create' %}">Create New Post</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'account_login' %}">Register / Login</a></li>
                        {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ request.user.get_absolute_url }}">Profile</a></li>
                                <li><a href="{% url 'account_logout' %}">Logout</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>

                    <form action="{% url 'experiment:home' %}" class="navbar-form navbar-right form-inline" role="search">
                        <div class="form-group">
                            {% for field in search_form %}
                                {{field}}
                            {% endfor %}
                        </div>
                        <div class="btn-group">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Advanced Search</a></li>
                            </ul>
                        </div>
                    </form>
                </div>
            </nav>
            {% endblock %}

            {% block content %}
            <h1>Hello, world!</h1>
            {% endblock %}

            {% block footer %}
            <div class="row footer">
                <div class="col-md-12">
                    <p>Open Networking Lab 2013
                </div>
            </div>
            {% endblock %}
        {% endblock %}
    </body>
</html>