experiment/urls.py
from django.conf.urls import patterns, include, url
import views
import views_s3

urlpatterns = patterns("",
    url(r"^$", views.ExperimentHome.as_view(), name="home"),
    url(r"^create/$", views.ExperimentCreate.as_view(), name="create"),
    url(r"^(?P<experiment_id>\d+)/$", views.ExperimentDetail.as_view(), name="detail"),
    url(r"^(?P<experiment_id>\d+)/update/$", views.ExperimentUpdate.as_view(), name="update"),

    url(r"^(?P<experiment_id>\d+)/image/$", views.ExperimentDetail.as_view(), name="image-home"),
    url(r"^(?P<experiment_id>\d+)/image/upload/$", views_s3.index, name="image-upload"),
    url(r"^(?P<experiment_id>\d+)/image/upload/init_multipart/$", views_s3.init_multipart, name="image-upload-init"),
    url(r"^(?P<experiment_id>\d+)/image/upload/send_chunk/$", views_s3.send_chunk, name="image-upload-send"),
    url(r"^(?P<experiment_id>\d+)/image/upload/complete_file/$", views_s3.complete_file, name="image-upload-complete"),
    url(r"^(?P<experiment_id>\d+)/image/upload/report/$", views_s3.report, name="image-upload-report")
)

experiment_repo/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url = reverse_lazy("experiment:home")), name = "repo-home"),
    url(r"^experiment/", include("experiment.urls", namespace = "experiment")),
    url(r"^users/", include("experiment_user.urls", namespace = "experiment_user")),
    url(r"^accounts/", include("allauth.urls")),

    # For admin
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

experiment/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.query import Q
from django.utils import timezone

import os

class Experiment(models.Model):
    title = models.CharField(max_length = 255, blank = False)
    description = models.TextField(max_length = 4096, blank = False)
    instruction = models.TextField(max_length = 2048, blank = False)
    paper = models.FileField(upload_to = "paper/%Y/%m/%d", blank = True)
    created_date = models.DateTimeField()
    owners = models.ManyToManyField(User)

    class Meta:
        ordering = ["-created_date"]

    def paper_filename(self):
        return os.path.basename(self.paper.name)
    def get_absolute_url(self):
        return reverse("experiment:detail", args=[str(self.id)])

    @staticmethod
    def simple_search(query):
        return Experiment.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) | 
                Q(instruction__icontains=query) | Q(tag__name__exact=query)).distinct()

class Tag(models.Model):
    name = models.CharField(max_length = 255, primary_key=True, blank = False)
    experiments = models.ManyToManyField(Experiment)

    @staticmethod
    def exist(name):
        try:
            Tag.objects.get(pk = name)
            return True
        except Tag.DoesNotExist:
            return False

class S3File(models.Model):
    experiment = models.OneToOneField(Experiment)
    url = models.CharField(max_length = 2048)
    key = models.CharField(max_length = 2048)

experiment/forms.py
from django import forms
from django.utils import timezone

from utils.forms import *
from .models import *

class ExperimentForm(forms.ModelForm):
    title = BootstrapCharField(max_length = 255, required = True)
    paper = forms.FileField(required = False)
    description = BootstrapTextField(max_length = 4096, required = True)
    instruction = BootstrapTextField(max_length = 2048, required = True)

    class Meta:
        model = Experiment
        fields = ["title", "paper", "description", "instruction",]

    def __init__(self, *args, **kwargs):
        tag_initial = "" if "tags" not in kwargs else kwargs.pop("tags")

        super(ExperimentForm, self).__init__(*args, **kwargs)
        self.fields["tags"] = BootstrapCharField(max_length = 1024, required = False, initial = tag_initial)

    def save(self, commit = True):
        m = super(ExperimentForm, self).save(commit = False)
        m.created_date = timezone.now()
        m.save()

        tags = []
        tag_names = self.cleaned_data["tags"].split()
        for tag_name in tag_names:
            tag, _ = Tag.objects.get_or_create(name = tag_name)
            tags.append(tag)
        m.tag_set = tags
        return m

experiment/views.py
from django.http import HttpResponseRedirect
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from utils.views import *

from .forms import *
from .models import *

class ExperimentHome(ExperimentSearch, ListView):
    model = Experiment
    context_object_name = "experiments"

    def get_queryset(self):
        if "query" in self.request.GET:
            q = self.request.GET["query"]
            return Experiment.simple_search(q)
        return Experiment.objects.all()

class ExperimentDetail(ExperimentSearch, DetailView):
    slug_url_kwarg = "experiment_id"
    slug_field = "id"
    model = Experiment
    context_object_name = "experiment"

class ExperimentCreate(ExperimentSearch, CreateView):
    form_class = ExperimentForm
    template_name = "experiment/experiment_create_form.html"

    def form_valid(self, form):
        self.object = form.save()
        self.object.owners.add(self.request.user)
        return super(ExperimentCreate, self).form_valid(form)

class ExperimentUpdate(ExperimentSearch, UpdateView):
    slug_url_kwarg = "experiment_id"
    slug_field = "id"
    model = Experiment
    form_class = ExperimentForm
    template_name = "experiment/experiment_update_form.html"

    def get_form_kwargs(self):
        kwargs = super(ExperimentUpdate, self).get_form_kwargs()
        kwargs["tags"] = " ".join(tag.name for tag in self.object.tag_set.all())
        return kwargs

experiment/templates/experiment/base.html
{% extends "base/base.html" %}
{% block navbar-home-attr %}
    class="active"
{% endblock %}

experiment/templates/experiment/experiment_create_form.html
{% extends "experiment/experiment_form.html" %}

{% block title_text %}
    New Post
{% endblock %}

experiment/templates/experiment/experiment_detail.html
{% extends "experiment/base.html" %}

{% block title_text %}
    {{ experiment.title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-10">
                    <h2>{{ experiment.title }}</h2>
                    <a href="{% url 'experiment:update' experiment_id=experiment.id %}">
                        <button type="button" class="btn btn-primary">
                        Edit Details
                        </button>
                    </a>

                    {% if experiment.s3file %}
                    <a href="{{ experiment.s3file.url }}" download>
                        <button type="button" class="btn btn-primary">
                        Download Image
                        </button>
                    </a>

                    <a href="{% url 'experiment:image-upload' experiment_id=experiment.id %}">
                        <button type="button" class="btn btn-primary">
                        Replace Image
                        </button>
                    </a>
                    {% else %}
                    <a href="{% url 'experiment:image-upload' experiment_id=experiment.id %}">
                        <button type="button" class="btn btn-primary">
                        Upload Image
                        </button>
                    </a>
                    {% endif %}
                </div>
                <div class="col-md-2">
                    {{ experiment.created_date }}
                </div>
            </div>

            <br>

            <div class="row">
                <div class="col-md-12">
                    Paper: {% if experiment.paper %} <a href="{{ experiment.paper.url }}"> {{ experiment.paper_filename }} </a> {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    Authors:
                    {% for owner in experiment.owners.all %}
                        <em><a href="{{ owner.get_absolute_url }}">{{ owner.username }}</a></em>
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    Tags:
                    {% for tag in experiment.tag_set.all %}
                        <em>{{tag.name}}</em>
                    {% endfor %}
                </div>
            </div>

            <h3>Description</h3>
            <div class="row">
                <div class="col-md-12">
                    {{ experiment.description }}
                </div>
            </div>

            <h3>Replication Instruction</h3>
            <div class="row">
                <div class="col-md-12">
                    {{ experiment.instruction }}
                </div>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}

experiment/templates/experiment/experiment_form.html
{% extends "experiment/base.html" %}

{% block navbar-home-attr %}
{% endblock %}
{% block navbar-create-attr %}
    class="active"
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" role="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

experiment/templates/experiment/experiment_list.html
{% extends "experiment/base.html" %}

{% block title_text %}
    Home
{% endblock %}

{% block content %}
    {% for experiment in experiments %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-10">
                    <a href="{{ experiment.get_absolute_url }}">
                        <h3>{{ experiment.title }}</h3>
                    </a>
                </div>
                <div class="col-md-2">
                    {{ experiment.created_date }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    {{ experiment.description }}
                </div>
            </div>

            <br>
            <div class="row">
                <div class="col-md-12">
                    Tags:
                    {% for tag in experiment.tag_set.all %}
                        <em>{{tag.name}}</em>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}
{% endblock %}

experiment/templates/experiment/experiment_update_form.html
{% extends "experiment/experiment_form.html" %}

{% block title_text %}
    Update Post
{% endblock %}