experiment/urls.py
from django.conf.urls import patterns, include, url
import views
import views_s3

urlpatterns = patterns("",
    url(r"^$", views.ExperimentHome.as_view(), name="home"),
    url(r"^create/$", views.ExperimentCreate.as_view(), name="create"),
    url(r"^(?P<experiment_id>\d+)/$", views.ExperimentDetail.as_view(), name="detail"),
    url(r"^(?P<experiment_id>\d+)/update/$", views.ExperimentUpdate.as_view(), name="update"),

    url(r"^(?P<experiment_id>\d+)/image/$", views.ExperimentDetail.as_view(), name="image-home"),
    url(r"^(?P<experiment_id>\d+)/image/upload/$", views_s3.index, name="image-upload"),
    url(r"^(?P<experiment_id>\d+)/image/upload/init_multipart/$", views_s3.init_multipart, name="image-upload-init"),
    url(r"^(?P<experiment_id>\d+)/image/upload/send_chunk/$", views_s3.send_chunk, name="image-upload-send"),
    url(r"^(?P<experiment_id>\d+)/image/upload/complete_file/$", views_s3.complete_file, name="image-upload-complete"),
    url(r"^(?P<experiment_id>\d+)/image/upload/report/$", views_s3.report, name="image-upload-report")
)

experiment_repo/urls.py
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^$", RedirectView.as_view(url = reverse_lazy("experiment:home")), name = "repo-home"),
    url(r"^experiment/", include("experiment.urls", namespace = "experiment")),
    url(r"^users/", include("experiment_user.urls", namespace = "experiment_user")),
    url(r"^accounts/", include("allauth.urls")),

    # For admin
    url(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    url(r"^admin/", include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

experiment/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.query import Q
from django.utils import timezone

import os

class Experiment(models.Model):
    title = models.CharField(max_length = 255, blank = False)
    description = models.TextField(max_length = 4096, blank = False)
    instruction = models.TextField(max_length = 2048, blank = False)
    paper = models.FileField(upload_to = "paper/%Y/%m/%d", blank = True)
    created_date = models.DateTimeField()
    owners = models.ManyToManyField(User)

    class Meta:
        ordering = ["-created_date"]

    def paper_filename(self):
        return os.path.basename(self.paper.name)
    def get_absolute_url(self):
        return reverse("experiment:detail", args=[str(self.id)])

    @staticmethod
    def simple_search(query):
        return Experiment.objects.filter(Q(title__icontains=query) | Q(description__icontains=query) | 
                Q(instruction__icontains=query) | Q(tag__name__exact=query)).distinct()

class Tag(models.Model):
    name = models.CharField(max_length = 255, primary_key=True, blank = False)
    experiments = models.ManyToManyField(Experiment)

    @staticmethod
    def exist(name):
        try:
            Tag.objects.get(pk = name)
            return True
        except Tag.DoesNotExist:
            return False

class S3File(models.Model):
    experiment = models.OneToOneField(Experiment)
    url = models.CharField(max_length = 2048)
    key = models.CharField(max_length = 2048)

experiment/forms.py
from django import forms
from django.utils import timezone

from utils.forms import *
from .models import *

class ExperimentForm(forms.ModelForm):
    title = BootstrapCharField(max_length = 255, required = True)
    paper = forms.FileField(required = False)
    description = BootstrapTextField(max_length = 4096, required = True)
    instruction = BootstrapTextField(max_length = 2048, required = True)

    class Meta:
        model = Experiment
        fields = ["title", "paper", "description", "instruction",]

    def __init__(self, *args, **kwargs):
        tag_initial = "" if "tags" not in kwargs else kwargs.pop("tags")

        super(ExperimentForm, self).__init__(*args, **kwargs)
        self.fields["tags"] = BootstrapCharField(max_length = 1024, required = False, initial = tag_initial)

    def save(self, commit = True):
        m = super(ExperimentForm, self).save(commit = False)
        m.created_date = timezone.now()
        m.save()

        tags = []
        tag_names = self.cleaned_data["tags"].split()
        for tag_name in tag_names:
            tag, _ = Tag.objects.get_or_create(name = tag_name)
            tags.append(tag)
        m.tag_set = tags
        return m

experiment/views.py
from django.http import HttpResponseRedirect
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from utils.views import *

from .forms import *
from .models import *

class ExperimentHome(ExperimentSearch, ListView):
    model = Experiment
    context_object_name = "experiments"

    def get_queryset(self):
        if "query" in self.request.GET:
            q = self.request.GET["query"]
            return Experiment.simple_search(q)
        return Experiment.objects.all()

class ExperimentDetail(ExperimentSearch, DetailView):
    slug_url_kwarg = "experiment_id"
    slug_field = "id"
    model = Experiment
    context_object_name = "experiment"

class ExperimentCreate(ExperimentSearch, CreateView):
    form_class = ExperimentForm
    template_name = "experiment/experiment_create_form.html"

    def form_valid(self, form):
        self.object = form.save()
        self.object.owners.add(self.request.user)
        return super(ExperimentCreate, self).form_valid(form)

class ExperimentUpdate(ExperimentSearch, UpdateView):
    slug_url_kwarg = "experiment_id"
    slug_field = "id"
    model = Experiment
    form_class = ExperimentForm
    template_name = "experiment/experiment_update_form.html"

    def get_form_kwargs(self):
        kwargs = super(ExperimentUpdate, self).get_form_kwargs()
        kwargs["tags"] = " ".join(tag.name for tag in self.object.tag_set.all())
        return kwargs

experiment/templates/s3/upload.html
{% extends "experiment/base.html" %}
{% load staticfiles %}

{% block title_text %}
    Upload Image
{% endblock %}

{% block extra_head %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/md5.js' %}"></script>
<script src="{% static 'js/S3MultipartUploader.js' %}"></script>

<script>
    $(function () {
        var fileDOM = $("#uploadFile");
        var settings = {
            s3AccessKey: "{{ AWS_ACCESS_KEY_ID }}",
            s3BucketName: "{{ S3_BUCKET_NAME }}",
            s3Folder: "{{ S3_FOLDER }}",
            serverBase: "{% url 'experiment:image-upload' experiment_id=experiment_id %}",

            onChange: function() {
                console.log("onChange");
            },

            onProgress: function(e) {
                var progress = e.loaded / e.total * 100;
                if(progress == 100) {
                    $("#progress").removeClass("progress-striped active");
                }
                else {
                    $("#progress").addClass("progress-striped active");
                }
                $("#bar").css("width", progress + "%");
                $("#bar").attr("aria-valuenow", progress);
                $("#progressText").html(~~progress + "%");
            },

            onDone: function(result) {
                $("#uploadButton").removeAttr("disabled");
                $("#message").html("Upload done!");

                var imageUrl = $("Location", result).text();
                var imageKey = $("Key", result).text();
                console.log("imageUrl: " + imageUrl);
                $.get("{% url 'experiment:image-upload-report' experiment_id=experiment_id %}",
                    {
                        "imageUrl": imageUrl,
                        "imageKey": imageKey
                    }
                ).done(function() {
                    console.log("Image URL reported to server");
                });
            }
        };

        var uploader = new S3MultipartUploader(fileDOM, settings);
        $("#uploadButton").click(function() {
            uploader.startUpload();
            $("#message").html("Uploading...");
            $(this).attr("disabled", "disabled");
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Upload Experiment Image</h1>

    <p>Select the file containing the experiment image you want to upload:</p>
    <input type="file" name="file" id="uploadFile">

    <br>
    <button class="btn btn-default" type="button" id="uploadButton">Start upload</button>

    <br><br>
    <p>Upload Progress: <span id="progressText"></span> </p>
    <div id="progress" class="progress">
        <div id="bar" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
        </div>
    </div>
    <p>
        Status: <span id="message">Upload not started</span>
    </p>
</div>
{% endblock %}